// EC-Lab — Reports tab: HTML report generator

(() => {
  async function populateSelector() {
    const samples = await DB.load();
    const sel = document.getElementById('report-sample');
    sel.innerHTML = '<option value="">Select a sample…</option>';
    samples.forEach(s => {
      const opt = document.createElement('option');
      opt.value = s.id;
      opt.textContent = `${s.sampleId || s.id.slice(-6)} — ${s.material}`;
      sel.appendChild(opt);
    });
  }

  function buildReport(s, opts) {
    const exps = s.experiments || [];
    const created  = new Date(s.createdAt).toLocaleString();
    const date     = new Date().toLocaleString();
    const author   = document.getElementById('rpt-author').value || 'EC-Lab';
    const meanCOP  = exps.length ? (exps.reduce((a, e) => a + (e.cop || 0), 0) / exps.length).toFixed(3) : '—';
    const meanSpan = exps.length ? (exps.reduce((a, e) => a + (e.span || 0), 0) / exps.length).toFixed(2) : '—';
    const totalCyc = (s.cycles || 0).toLocaleString();

    const expRows = exps.slice().reverse().map(e => `
      <tr>
        <td>${new Date(e.date).toLocaleString()}</td>
        <td>${(e.cycles||0).toLocaleString()}</td>
        <td>${e.cop != null ? e.cop.toFixed(3) : '—'}</td>
        <td>${e.span != null ? e.span.toFixed(2) + ' K' : '—'}</td>
        <td>${e.notes || ''}</td>
      </tr>`).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EC-Lab Report — ${s.sampleId || s.id.slice(-6)}</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; color: #1a2535; line-height: 1.6; }
  h1   { color: #007a62; border-bottom: 2px solid #007a62; padding-bottom: 8px; }
  h2   { color: #2c4a6e; margin-top: 32px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
  th   { background: #f0f6ff; color: #2c4a6e; text-align: left; padding: 8px 12px; border-bottom: 2px solid #c8d8ee; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
  td   { padding: 8px 12px; border-bottom: 1px solid #e8eef8; }
  tr:hover td { background: #f8fbff; }
  .kv  { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 14px; margin-top: 14px; }
  .kv-item { background: #f4f8ff; border-radius: 8px; padding: 12px 16px; }
  .kv-label { font-size: 10px; text-transform: uppercase; letter-spacing: .05em; color: #6a8aaa; display: block; margin-bottom: 4px; }
  .kv-value { font-size: 22px; font-weight: 700; color: #007a62; font-family: 'Courier New', monospace; }
  .kv-unit  { font-size: 11px; color: #8aabad; }
  .badge    { display: inline-block; background: #e8f5f1; color: #007a62; border-radius: 4px; padding: 2px 8px; font-size: 11px; font-weight: 600; }
  .footer   { margin-top: 40px; padding-top: 16px; border-top: 1px solid #dde; font-size: 12px; color: #8aabad; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<h1>Elastocaloric Polymer Film — Experiment Report</h1>
<p><strong>Sample:</strong> ${s.sampleId || '—'} &nbsp;|&nbsp; <strong>Material:</strong> <span class="badge">${s.material}</span> &nbsp;|&nbsp; <strong>Generated:</strong> ${date} &nbsp;|&nbsp; <strong>Author:</strong> ${author}</p>

<h2>Sample Specifications</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Created</td><td>${created}</td></tr>
  <tr><td>Thickness</td><td>${s.thickness ? s.thickness + ' mm' : '—'}</td></tr>
  <tr><td>Width × Length</td><td>${s.width && s.length ? s.width + ' mm × ' + s.length + ' mm' : '—'}</td></tr>
  <tr><td>Mass</td><td>${s.mass ? s.mass + ' g' : '—'}</td></tr>
  <tr><td>Target max strain</td><td>${s.maxStrain || '—'} %</td></tr>
  ${s.notes ? `<tr><td>Notes</td><td>${s.notes}</td></tr>` : ''}
</table>

<h2>Performance Summary</h2>
<div class="kv">
  <div class="kv-item"><span class="kv-label">Total cycles</span><span class="kv-value">${totalCyc}</span></div>
  <div class="kv-item"><span class="kv-label">Mean COP</span><span class="kv-value">${meanCOP}</span></div>
  <div class="kv-item"><span class="kv-label">Mean ΔT span</span><span class="kv-value">${meanSpan}</span><span class="kv-unit">K</span></div>
</div>

${opts.rpt_cop ? `
<h2>Experiment Log</h2>
<table>
  <thead><tr><th>Date</th><th>Cycles</th><th>COP</th><th>ΔT span</th><th>Notes</th></tr></thead>
  <tbody>${expRows || '<tr><td colspan="5">No experiments logged yet.</td></tr>'}</tbody>
</table>` : ''}

<div class="footer">
  Generated by EC-Lab · Institute of Microstructure Technology · KIT<br>
  Zero-emission Thermal Technologies (ZET) Group
</div>
</body>
</html>`;
  }

  document.getElementById('btn-gen-report').addEventListener('click', async () => {
    const sampleId = document.getElementById('report-sample').value;
    if (!sampleId) { alert('Select a sample first.'); return; }

    const samples = await DB.load();
    const s = samples.find(s => s.id === sampleId);
    if (!s) return;

    const opts = {
      rpt_dsc:     document.getElementById('rpt-dsc').checked,
      rpt_tensile: document.getElementById('rpt-tensile').checked,
      rpt_cop:     document.getElementById('rpt-cop').checked,
      rpt_notes:   document.getElementById('rpt-notes').checked,
    };

    const html = buildReport(s, opts);

    // Preview
    const preview = document.getElementById('report-preview');
    preview.innerHTML = `<div style="background:#fff;padding:24px;border-radius:8px;color:#1a2535;">${html.replace(/<(!DOCTYPE|html|head|body)[^>]*>/gi,'').replace(/<\/(html|head|body)>/gi,'')}</div>`;

    // Export
    const ts = new Date().toISOString().slice(0, 10);
    const saved = await window.api.fs.saveHtml(`ECLab_Report_${s.sampleId || s.id.slice(-6)}_${ts}.html`, html);
    if (saved) console.log(`Report saved: ${saved}`);
  });

  window.addEventListener('tab-change', e => {
    if (e.detail === 'reports') populateSelector();
  });
  window.addEventListener('samples-changed', populateSelector);
  populateSelector();
})();
